server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maven02?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 132511
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式
  #静态资源访问路径：用于告诉Spring Boot应该在何处查找静态资源文件,查找文件时会依赖于配置的先后顺序依次进行
  mvc:
    static-path-pattern: /static/**




mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.zcbigdata.mybits_demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

